### PR TITLE
adding support for client-side page creation, update, and supporting …

### PR DESCRIPTION
**Pull request by patrick-rodgers**
…changes.

#### Category
- [ ] Bug fix?
- [X] New feature?
- [ ] New sample?
- [ ] Documentation update?

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Here is support for client-side pages, there is a supporting docs page and tests as well. I have tested it as best I can but not exhaustively. Please have a look when you have a few minutes and let me know what you think. Thanks @koltyakov !

**Comment by koltyakov** [comment]
Hi @patrick-rodgers,
Thanks! I'll take a look over the weekend.

**Comment by patrick-rodgers** [comment]
Going to merge this for today's planned release, we can make updates as needed if issues are found, like always :)

**Comment by koltyakov** [comment]
Thanks, Patrik! I went through the changes (not all), some of them were great to know on my end and very informative. Thought I had less time than I wished to spend, so I didn't leave any valuable comment for you. But everything I've seen was in pretty good shape.

**Comment by patrick-rodgers** [comment]
cool cool, thanks!

**Pull request merged**
